### ISSUE TITLE
Location of tests

### ISSUE THREAD

**Issue by Cpt-xx** [fragmatyc/SDFL#3]
Hi Sylvain,

I was doing some playing around, just to get familiar with the code and I wanted to run the tests. However you seem to have decided against the regular Maven lay-out (which is project/main/src project/main/test) and decided to create two projects (one for the source and one for the tests).

This puzzles me a bit, can you explain to me/us what your vision was in separating the tests and the sources under test in two separate projects?

For now I cannot easily see how to test my modifications.

Kind regards,

Cor

**Comment by fragmatyc** [comment]
Hi Cor,
You can run the tests by either running the test class/method or the whole project. Regarding the separation of the tests suite, it's only a matter of choice. If you think that is a show stopper, please explain your point and we'll move it into the actual project, no worries!

Cheers!

**Comment by Cpt-xx** [comment]
What I tried to do was running the tests from the pom-file in the test-directory (running mvn clean verify) and there it failed for several reasons (I will provide the output at a later moment).
What I personally like about the regular way of project setup is that I can use the same Idea-project for both modifying code and running the test. 
You might have a number of good reasons for setting up the project the way you did and before I would like to embark on reconfiguring the project(s) I would like to hear your reasons. It is a showstopper if I (and presumably others) cannot easily and quickly run tests.

**Comment by fragmatyc** [comment]
- I created src/test/java and src/main/java, and copied the packages with their classes in the appropriated source folder
- I changed the POM to add the test dependencies
- I ran mvn clean verify and the test suite ran successfully

<pre><code>
Results :
Tests run: 105, Failures: 0, Errors: 0, Skipped: 1
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ SimpleDataFixLanguage ---
[INFO] Building jar: C:\Users\closy2\Desktop\ sdfl-code\Git\SDFL\SimpleDataFixLa
nguage\target\SimpleDataFixLanguage-0.0.1-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.213 s
[INFO] Finished at: 2016-02-03T20:37:41-05:00
[INFO] Final Memory: 18M/184M
[INFO] ------------------------------------------------------------------------
</code></pre>

**Comment by Cpt-xx** [comment]
Is this now the new setup? If so, I will fetch this new stuff and continue :+1:

**Comment by fragmatyc** [comment]
Yup, I changed the structure to make it run when compiling the with Maven. It seems like it's working, but please, tell me if it works out of the box with your IDE.

**Comment by Cpt-xx** [comment]
:+1: I will tell you the outcome. It should behave in any given IDE supporting Maven though, so if it does for yours, I'm pretty confident it will work in mine.

**Comment by fragmatyc** [comment]
Considered completed. Closing issue!
