### ISSUE TITLE
File DONE_WDMS_END_IDENT_PARTS 7.xls not in test

### ISSUE THREAD

**Issue by Cpt-xx** [fragmatyc/SDFL#6]
Hi, could you make sure that the file DONE_WDMS_END_IDENT_PARTS 7.xls is placed in src/test/resources? 
That way we can all use the same file as input. As src/test/resources should be part of the default class-path we don't need to have an E-drive. For me that would be impossible as I've got a Linux machine at home. Using platform dependant materials in an open source project is not a very often practised convention :wink:  .

For instance the ImportInputFileLoaderFileSystemTest in its current form can presumably only be ran by you (as I neither have an E-drive nor the file itself).

**Comment by fragmatyc** [comment]
Hi Cor, this test is marked as "Skip". You should not bother as a test case should not access physical resources.

**Comment by Cpt-xx** [comment]
Then I would suggest that you remove this test alltogether. Having tests in "production code" which are not to be run (by means of @Ignore or otherwise) will only cause confusion (such as "the file is not there, it should be... shouldn't it?").
If a test is there, it should be active.

You are only partially right though, physical resources are very usefull, especially if the class under test accesses a phycial resource. We should however only allow physical resources which are stored platform independent (e.g. in src/test/resources).

**Comment by fragmatyc** [comment]
Yes, it can be removed.

**Comment by Cpt-xx** [comment]
I would say: go ahead :smile_cat:

**Comment by fragmatyc** [comment]
Removed as per you recommendation. Closing this issue.
